---
title: Teguh Febbyan Valentino
bio: Fullstack Developer, Informatics Engineering Degree<br>Based in Bali Indonesia
description: I'm a Detective also murderer.
reading_time: true
words_per_minute: 200
logo: assets/img/image.png
background: assets/img/tilled.jpeg
tiled_bg: true
locale: en_US
url: https://teguhfv.github.io
twitter:
  username: teguhfv
  card: summary
social:
  name: Teguh Febbyan Valentino
  links:
    - https://twitter.com/teguhfv
    - https://www.facebook.com/teguhfebbyanvalentino
    - https://www.linkedin.com/in/teguh-febbyan-valentino
    - https://plus.google.com/+TeguhFebbyanValentino
    - https://github.com/teguhfv
plugins_dir:
 -jekyll-sitemap
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
disqus_shortname: teguhfv
google:
  plus: 
email: teguhfv@gmail.com
twitter: teguhfv
facebook: teguhfebbyanvalentino
github-url: teguhfv
linkedin: teguh-febbyan-valentino
instagram: teguhfv
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
- jekyll-analytics
- jekyll-seo-tag
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
jekyll_analytics:
  GoogleAnalytics:
    id: UA-129079004-1
    anonymizeIp: false
